---
operator: 5HmxV7yUHQnJYnVZVqDW2zd2qGznrvtqKLgyzFKnCS7jCAtT
operator_phrase: boring crush turtle chronic dignity taxi glide hill exist twenty sure movie
substrate_endpoint: "wss://mainnet-dev.deeper.network:443"
